# numpy exercise

In [3]:
import numpy as np

## 1. Literal array definition

In [3]:
A = np.array([
    [1, 3, 5, 7],
    [2, 4, 6, 8],
    [3, 5, 7, 9]
])

A

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [3, 5, 7, 9]])

In [4]:
b = np.array([1, 2, 3, 4])
b

array([1, 2, 3, 4])

## 2. Array dimensions

numpy.ndarray.**shape**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html

In [5]:
# 2-D array
A.shape

(3, 4)

In [6]:
# dimensions unpacking
n, m = A.shape

print('rows:', n)
print('cols:', m)

rows: 3
cols: 4


In [7]:
# 1-D array
b.shape

(4,)

In [5]:
c = b.reshape(1, -1)
c

array([[1, 2, 3, 4]])

In [9]:
# 2-D array
c.shape

(1, 4)

**Recommendation: avoid using 1-D arrays where possible** due to complex matrix operations rules: result may be surprising/unpredictable
  
use numpy.**reshape** to transform them into 2-D  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

2.1. Create matrix $C$ by reshaping vector $c$ into dimensions $2 \times 2$

In [12]:
C = np.reshape(c, (2, 2)) 
C

array([[1, 2],
       [3, 4]])

## 3. Matrix indexing and slicing

See docs:  
https://docs.scipy.org/doc/numpy-1.10.0/user/basics.indexing.html

or find some easier tutorial

3.1. Select $A_{1, 2}$

In [13]:
A[1, 2]

6

3.2. Select second column of $A$

In [14]:
A[:, 1]

array([3, 4, 5])

3.3. Select first two columns of $A$

In [23]:
A[:, :2]

array([[1, 3],
       [2, 4],
       [3, 5]])

3.4. Select last row of $A$

In [25]:
A[-2, :]

array([2, 4, 6, 8])

3.5. Select 1st and 3rd columns of $A$

In [30]:
A[:, [0, 2]]

array([[1, 5],
       [2, 6],
       [3, 7]])

## 4. Matrix operations
4.1. Transpose matrices $A, c$: get $A^T, c^T$  

numpy.ndarray.**transpose**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.transpose.html

numpy.ndarray.**T** (shortcut)  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html

In [44]:
A.transpose()
c.T

array([[1],
       [2],
       [3],
       [4]])

4.2. Multiply $A \cdot c^T$ (don't forget to transpose $c$ to make dimensions match)

numpy.**dot**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

In [51]:
np.dot(A, c.T)

array([[50],
       [60],
       [70]])

4.3. Multiply $A * D$ elementwise

numpy.**multiply**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.multiply.html

Find shortcut for matrix elementwise multiplication!

In [55]:
D = np.array([
    [1, 2, 1, 2],
    [1, 2, 1, 2],
    [1, 2, 1, 2]
])
A

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [3, 5, 7, 9]])

In [54]:
np.multiply(A, D)

array([[ 1,  6,  5, 14],
       [ 2,  8,  6, 16],
       [ 3, 10,  7, 18]])

4.4. Add and subtract matrices: $A + D, A - D$  

numpy.**add**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.add.html

numpy.**subtract**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.subtract.html

Find shortcuts!

In [60]:
np.add(A,D)
np.subtract(A,D)

array([[0, 1, 4, 5],
       [1, 2, 5, 6],
       [2, 3, 6, 7]])

4.5. Divide $A$ by $D$ elementwise  

numpy.**divide**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.divide.html  

Find shortcut!

In [62]:
np.divide(A,D)

array([[1. , 1.5, 5. , 3.5],
       [2. , 2. , 6. , 4. ],
       [3. , 2.5, 7. , 4.5]])

## 5. Broadcasting

See docs:  
https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [3, 5, 7, 9]])

In [65]:
# 1 is repeated 3 x 4 times to make dimensions match
A + 1

array([[ 2,  4,  6,  8],
       [ 3,  5,  7,  9],
       [ 4,  6,  8, 10]])

In [64]:
A * 2

array([[ 2,  6, 10, 14],
       [ 4,  8, 12, 16],
       [ 6, 10, 14, 18]])

In [66]:
A ** 2

array([[ 1,  9, 25, 49],
       [ 4, 16, 36, 64],
       [ 9, 25, 49, 81]], dtype=int32)

In [67]:
# c is stacked 3 times to make dimensions match
A + c

array([[ 2,  5,  8, 11],
       [ 3,  6,  9, 12],
       [ 4,  7, 10, 13]])

## 6. Automated matrix creation

6.1. Generate $Z \in \mathbb{R}^{2 \times 4}$ matrix filled with zeros

numpy.**zeros**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html

In [69]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

6.2. Generate $U \in \mathbb{R}^{5 \times 4}$ matrix filled with uniformely distributed values in range $(-8, 12)$

numpy.random.**uniform**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.uniform.html

In [77]:
u=np.random.uniform(-8, 12, (5,4))
u

array([[-1.44028907, -1.35686111,  8.70022966,  0.88389639],
       [ 0.43466431,  9.1225368 , -0.71226691,  7.64178812],
       [ 2.3363571 , -4.85639774,  4.77252049, -6.64160325],
       [-5.03823347, -7.73198809,  6.84091407, -4.56207095],
       [-7.51539964,  2.57532367,  7.60738312, -1.82886314]])

6.3. Generate $N \in \mathbb{R}^{8 \times 3}$ matrix filled with normally distributed values with $\mu = 0$ and $\sigma = 5$

numpy.random.**normal**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.normal.html

In [73]:
np.random.normal(0, 5, (8,3))

array([[12.51956408, -4.7333815 ,  6.13037107],
       [ 9.01615597, -4.93663204,  0.26602045],
       [ 0.20655364,  8.75751032,  0.68831623],
       [-0.36629103, -0.59390315,  0.78097465],
       [-2.1474963 ,  1.80475968, -6.43369206],
       [ 2.14483902,  3.48531641,  0.87733404],
       [ 7.85472129, -3.48299253, -6.06297332],
       [ 1.72829661,  3.16911701, -0.95014554]])

## 7. Matrix aggregate functions

7.1. Find mean, min and max values in $U$

numpy.**mean**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html

numpy.ndarray.**min**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.min.html

numpy.ndarray.**max**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.max.html

In [78]:
np.max(u)

9.122536796184267

7.2. Find mean and standard deviation for each column of $N$

numpy.**std**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html

In [81]:
np.mean(n)
np.std(u)

5.438212293608374

7.3. Find sum of all elements of $U$, also all row-wise and column-wise sums

numpy.**sum**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html

In [82]:
np.sum(u)

9.231640350120333

## 8. Other helpful functions

8.1. Create matrix $S$:
$S_{i, j}=
\begin{cases}
    1, & \text{if $N_{i, j} \ge 0$},\\
    -1, & \text{if $N_{i, j} < 0$}.
\end{cases}
$

numpy.**where**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html

In [84]:
a = np.arange(-10, 10)
np.where(a>=0, 1, -1)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1])

In [7]:
A = np.array([1,2,3,4])
B = np.array([1,2,3,4])

A[:3] * B[:3]

array([1, 4, 9])